# Generated by Django 6.0.6 on 2026-06-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscribed_at",
            new_name="subscription_date",
        ),
    ]
