# Generated by Django 6.0.6 on 2026-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_publisher_user_alter_publisher_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalist",
            name="publishers",
            field=models.ManyToManyField(
                blank=True, related_name="journalists", to="news.publisher"
            ),
        ),
    ]
